const { solution } = require("./binary-gap")

it("should return binary gaps to given number", () => {
  expect(solution(1)).toBe(0)
  expect(solution(2)).toBe(0)
  expect(solution(3)).toBe(0)
  expect(solution(4)).toBe(0)
  expect(solution(5)).toBe(1)
  expect(solution(6)).toBe(0)
  expect(solution(7)).toBe(0)
  expect(solution(8)).toBe(0)
  expect(solution(9)).toBe(2)
  expect(solution(11)).toBe(1)
  expect(solution(51)).toBe(2)
  expect(solution(57)).toBe(2)
  expect(solution(71)).toBe(3)
  expect(solution(147)).toBe(2)
  expect(solution(483)).toBe(3)
  expect(solution(647)).toBe(4)
  expect(solution(32903)).toBe(7)
})
